apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: yhunlu/auth
      context: auth
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*