apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: us.gcr.io/trustytix/auth
      context: auth
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
  # local:
  #   push: false
  googleCloudBuild:
    projectId: trustytix
manifests:
  rawYaml:
    - ./infra/k8s/*